//! `mdvs scaffold hook` — print the per-platform PostToolUse hook config.
//!
//! The emitted config calls `mdvs hook handle --platform <name> --kind
//! <kind>` for each matcher. No shell scripts are generated; the runtime
//! lives in mdvs itself ([`crate::cmd::hook::handle`]).
//!
//! Refuses for platforms without a shell-hook surface (OpenCode's
//! TypeScript plugin API, Antigravity's undocumented hook spec) — both
//! cases fail with a pointer message explaining the user should still
//! install the skill and snippet via `mdvs scaffold skill|snippet`.

use std::io::Write;

use anyhow::{Context, Result};
use serde_json::{Map, Value, json};

use crate::scaffold::{HookConfigFormat, HooksConfig, Platform};

/// Print the hook config JSON for `platform_name` to `stdout`. Writes a
/// short install hint to `stderr`. Returns an error if the platform has
/// no `[hooks]` section (OpenCode, Antigravity).
pub fn run<W: Write, E: Write>(
    stdout: &mut W,
    stderr: &mut E,
    platform_name: &str,
) -> Result<()> {
    let platform = Platform::load(platform_name)?;
    let hooks = platform.hooks.as_ref().ok_or_else(|| {
        anyhow::anyhow!(
            "platform '{}' has no shell-hook surface. \
             Skill and snippet still install via `mdvs scaffold skill --platform {0}` and \
             `mdvs scaffold snippet --platform {0}`. Hook support depends on the harness adding \
             a documented PostToolUse-style mechanism.",
            platform.meta.name
        )
    })?;

    let config = build_config(&platform.meta.name, hooks);
    let rendered = match hooks.config_format {
        HookConfigFormat::Json => serde_json::to_string_pretty(&config)?,
        HookConfigFormat::Toml => toml::to_string_pretty(&config)?,
    };
    stdout.write_all(rendered.as_bytes()).context("writing hook config to stdout")?;
    stdout.write_all(b"\n").ok();

    writeln!(
        stderr,
        "Merge into: {} (under {})",
        hooks.config_path, platform.meta.display_name
    )
    .context("writing install hint")?;

    Ok(())
}

/// Build the JSON config block for a platform's hooks.
///
/// Shape (Claude Code / Codex / Cursor all converged on this with only
/// the event-name capitalization differing):
///
/// ```text
/// {
///   "_comment": "...",
///   "hooks": {
///     "<event_name>": [
///       { "matcher": "<matcher_validate>",
///         "hooks": [{ "type": "command", "command": "mdvs hook handle --platform <p> --kind validate" }] },
///       { "matcher": "<matcher_search>",
///         "hooks": [{ "type": "command", "command": "mdvs hook handle --platform <p> --kind search-nudge" }] }
///     ]
///   }
/// }
/// ```
fn build_config(platform_name: &str, hooks: &HooksConfig) -> Value {
    let comment = format!(
        "mdvs PostToolUse hooks generated by `mdvs scaffold hook --platform {platform_name}`. \
         Merge into {} under the existing `hooks` key. Both hooks self-scope by walking up \
         from the agent's cwd to find mdvs.toml; they stay silent outside an mdvs vault.",
        hooks.config_path
    );

    let validate_entry = json!({
        "matcher": hooks.matcher_validate,
        "hooks": [{
            "type": "command",
            "command": format!("mdvs hook handle --platform {platform_name} --kind validate"),
        }],
    });
    let search_entry = json!({
        "matcher": hooks.matcher_search,
        "hooks": [{
            "type": "command",
            "command": format!("mdvs hook handle --platform {platform_name} --kind search-nudge"),
        }],
    });

    let mut event_map = Map::new();
    event_map.insert(
        hooks.event_name.clone(),
        Value::Array(vec![validate_entry, search_entry]),
    );

    json!({
        "_comment": comment,
        "hooks": Value::Object(event_map),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hook_emits_valid_json_for_claude_code() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "claude-code").unwrap();
        let parsed: Value = serde_json::from_slice(&out).expect("output should be valid JSON");

        // Comment field present.
        assert!(parsed["_comment"].is_string());
        assert!(
            parsed["_comment"].as_str().unwrap().contains(".claude/settings.json"),
            "comment should reference the install path"
        );

        // PostToolUse with the two hooks under it.
        let post = &parsed["hooks"]["PostToolUse"];
        assert!(post.is_array());
        let entries = post.as_array().unwrap();
        assert_eq!(entries.len(), 2, "expected validate + search-nudge entries");
        assert_eq!(entries[0]["matcher"], "Edit|Write|MultiEdit");
        assert_eq!(entries[1]["matcher"], "Bash");

        // The command for each entry calls mdvs hook handle.
        assert!(
            entries[0]["hooks"][0]["command"]
                .as_str()
                .unwrap()
                .contains("mdvs hook handle --platform claude-code --kind validate")
        );
        assert!(
            entries[1]["hooks"][0]["command"]
                .as_str()
                .unwrap()
                .contains("mdvs hook handle --platform claude-code --kind search-nudge")
        );

        // Stderr hint.
        let hint = String::from_utf8(err).unwrap();
        assert!(hint.contains(".claude/settings.json"), "{hint}");
    }

    #[test]
    fn hook_emits_camelcase_event_name_for_cursor() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "cursor").unwrap();
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        // Cursor uses camelCase as the event key.
        assert!(parsed["hooks"]["postToolUse"].is_array());
        assert!(parsed["hooks"]["PostToolUse"].is_null());
        assert_eq!(
            parsed["hooks"]["postToolUse"][0]["hooks"][0]["command"]
                .as_str()
                .unwrap(),
            "mdvs hook handle --platform cursor --kind validate"
        );
    }

    #[test]
    fn hook_uses_codex_config_path() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "codex").unwrap();
        let hint = String::from_utf8(err).unwrap();
        assert!(hint.contains(".codex/hooks.json"), "{hint}");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        // Codex shares Claude Code's PascalCase event name.
        assert!(parsed["hooks"]["PostToolUse"].is_array());
    }

    #[test]
    fn hook_refuses_for_opencode_with_pointer() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        let res = run(&mut out, &mut err, "opencode");
        let e = res.unwrap_err();
        let msg = format!("{e}");
        assert!(msg.contains("opencode"), "{msg}");
        assert!(msg.contains("no shell-hook surface"), "{msg}");
        // The error should still point users at scaffold skill / snippet
        // (which DO work for opencode).
        assert!(msg.contains("mdvs scaffold skill"), "{msg}");
        assert!(msg.contains("mdvs scaffold snippet"), "{msg}");
    }

    #[test]
    fn hook_refuses_for_antigravity() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        let res = run(&mut out, &mut err, "antigravity");
        assert!(res.is_err());
    }

    #[test]
    fn hook_errors_on_unknown_platform() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        let res = run(&mut out, &mut err, "made-up-platform");
        assert!(res.is_err());
    }

    /// Round-trip: the emitted command strings should match the form
    /// `mdvs hook handle` actually accepts. Smoke check by parsing the
    /// command via clap.
    #[test]
    fn emitted_commands_parse_as_clap_input() {
        // Quick check: every emitted command starts with `mdvs hook handle
        // --platform <name> --kind <kind>` with `kind` one of the two
        // values clap knows about.
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "claude-code").unwrap();
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        for entry in parsed["hooks"]["PostToolUse"].as_array().unwrap() {
            let cmd = entry["hooks"][0]["command"].as_str().unwrap();
            assert!(cmd.starts_with("mdvs hook handle --platform claude-code --kind "));
            let kind = cmd
                .strip_prefix("mdvs hook handle --platform claude-code --kind ")
                .unwrap();
            assert!(
                kind == "validate" || kind == "search-nudge",
                "kind must match clap's value-enum: {kind}"
            );
        }
    }
}
