//! `mdvs scaffold hook` — print the per-platform PostToolUse hook config.
//!
//! The emitted config calls `mdvs hook handle --platform <name> --kind
//! <kind>` for each matcher. No shell scripts are generated; the runtime
//! lives in mdvs itself ([`crate::cmd::hook::handle`]).
//!
//! Refuses for platforms without a shell-hook surface (OpenCode's
//! TypeScript plugin API, Antigravity's undocumented hook spec) — both
//! cases fail with a pointer message explaining the user should still
//! install the skill and snippet via `mdvs scaffold skill|snippet`.

use std::collections::HashMap;
use std::io::Write;

use anyhow::{Context, Result};
use serde_json::{Map, Value};

use crate::scaffold::{HookConfigFormat, HooksConfig, Platform, template};

/// Print the hook config JSON for `platform_name` to `stdout`. Writes a
/// short install hint to `stderr`. Returns an error if the platform has
/// no `[hooks]` section (OpenCode, Antigravity).
pub fn run<W: Write, E: Write>(
    stdout: &mut W,
    stderr: &mut E,
    platform_name: &str,
) -> Result<()> {
    let platform = Platform::load(platform_name)?;
    let hooks = platform.hooks.as_ref().ok_or_else(|| {
        anyhow::anyhow!(
            "platform '{}' has no shell-hook surface. \
             Skill and snippet still install via `mdvs scaffold skill --platform {0}` and \
             `mdvs scaffold snippet --platform {0}`. Hook support depends on the harness adding \
             a documented PostToolUse-style mechanism.",
            platform.meta.name
        )
    })?;

    let config = build_config(&platform.meta.name, hooks);
    let rendered = match hooks.config_format {
        HookConfigFormat::Json => serde_json::to_string_pretty(&config)?,
        HookConfigFormat::Toml => toml::to_string_pretty(&config)?,
    };
    stdout.write_all(rendered.as_bytes()).context("writing hook config to stdout")?;
    stdout.write_all(b"\n").ok();

    writeln!(
        stderr,
        "Merge into: {} (under {})",
        hooks.config_path, platform.meta.display_name
    )
    .context("writing install hint")?;

    Ok(())
}

/// Build the hooks config snippet for a platform by substituting into
/// the platform's bundled `hooks.config` template.
///
/// The template (in `platform.toml`) declares the full per-harness JSON
/// shape, including any wrapper structure, matcher conventions, and
/// version fields. mdvs only fills in the two command strings via the
/// `<<COMMAND_VALIDATE>>` and `<<COMMAND_SEARCH>>` placeholders.
///
/// A `_comment` field is added at the top of the resulting object (if it
/// is one) so users opening the generated snippet see where to install
/// it. The comment is added programmatically rather than templated so
/// each platform.toml stays focused on the actual schema.
fn build_config(platform_name: &str, hooks: &HooksConfig) -> Value {
    let vars: HashMap<&str, Option<String>> = HashMap::from([
        (
            "COMMAND_VALIDATE",
            Some(format!(
                "mdvs hook handle --platform {platform_name} --kind validate"
            )),
        ),
        (
            "COMMAND_SEARCH",
            Some(format!(
                "mdvs hook handle --platform {platform_name} --kind search-nudge"
            )),
        ),
    ]);

    let mut config = template::substitute(&hooks.config, &vars);

    // Inject a leading _comment field so users see what to do with the
    // emitted snippet. Only applies to object-rooted templates (every
    // platform we ship is one).
    let comment = format!(
        "mdvs PostToolUse hooks generated by `mdvs scaffold hook --platform {platform_name}`. \
         Merge into {} under the existing `hooks` key. Both hooks self-scope by walking up \
         from the agent's cwd to find mdvs.toml; they stay silent outside an mdvs vault.",
        hooks.config_path
    );
    if let Value::Object(map) = &mut config {
        // Rebuild with _comment first for readability.
        let mut with_comment = Map::with_capacity(map.len() + 1);
        with_comment.insert("_comment".into(), Value::String(comment));
        for (k, v) in std::mem::take(map) {
            with_comment.insert(k, v);
        }
        *map = with_comment;
    }
    config
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hook_emits_valid_json_for_claude_code() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "claude-code").unwrap();
        let parsed: Value = serde_json::from_slice(&out).expect("output should be valid JSON");

        // Comment field present.
        assert!(parsed["_comment"].is_string());
        assert!(
            parsed["_comment"].as_str().unwrap().contains(".claude/settings.json"),
            "comment should reference the install path"
        );

        // PostToolUse with the two hooks under it.
        let post = &parsed["hooks"]["PostToolUse"];
        assert!(post.is_array());
        let entries = post.as_array().unwrap();
        assert_eq!(entries.len(), 2, "expected validate + search-nudge entries");
        assert_eq!(entries[0]["matcher"], "Edit|Write|MultiEdit");
        assert_eq!(entries[1]["matcher"], "Bash");

        // The command for each entry calls mdvs hook handle.
        assert!(
            entries[0]["hooks"][0]["command"]
                .as_str()
                .unwrap()
                .contains("mdvs hook handle --platform claude-code --kind validate")
        );
        assert!(
            entries[1]["hooks"][0]["command"]
                .as_str()
                .unwrap()
                .contains("mdvs hook handle --platform claude-code --kind search-nudge")
        );

        // Stderr hint.
        let hint = String::from_utf8(err).unwrap();
        assert!(hint.contains(".claude/settings.json"), "{hint}");
    }

    /// Cursor uses a flat matcher entry shape and a top-level `version`
    /// field — completely different from Claude Code's nested layout.
    /// The platform.toml template captures the difference; the scaffolder
    /// just substitutes commands in.
    #[test]
    fn hook_emits_cursor_flat_shape_with_version() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "cursor").unwrap();
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        // Top-level version: 1 (Cursor-specific).
        assert_eq!(parsed["version"], 1);
        // camelCase event key.
        assert!(parsed["hooks"]["postToolUse"].is_array());
        assert!(parsed["hooks"]["PostToolUse"].is_null());
        // Flat shape: command is a direct property of the matcher entry,
        // not nested inside a `hooks` array.
        let entry = &parsed["hooks"]["postToolUse"][0];
        assert_eq!(entry["matcher"], "Edit|Write|MultiEdit");
        assert_eq!(
            entry["command"].as_str().unwrap(),
            "mdvs hook handle --platform cursor --kind validate"
        );
        // The Claude-Code-style nested `hooks` array should NOT be present
        // on the matcher entry — that would be the wrong schema for Cursor.
        assert!(entry.get("hooks").is_none(), "cursor entries are flat, no nested hooks array");
    }

    #[test]
    fn hook_uses_codex_config_path() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "codex").unwrap();
        let hint = String::from_utf8(err).unwrap();
        assert!(hint.contains(".codex/hooks.json"), "{hint}");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        // Codex shares Claude Code's PascalCase event name.
        assert!(parsed["hooks"]["PostToolUse"].is_array());
    }

    #[test]
    fn hook_refuses_for_opencode_with_pointer() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        let res = run(&mut out, &mut err, "opencode");
        let e = res.unwrap_err();
        let msg = format!("{e}");
        assert!(msg.contains("opencode"), "{msg}");
        assert!(msg.contains("no shell-hook surface"), "{msg}");
        // The error should still point users at scaffold skill / snippet
        // (which DO work for opencode).
        assert!(msg.contains("mdvs scaffold skill"), "{msg}");
        assert!(msg.contains("mdvs scaffold snippet"), "{msg}");
    }

    #[test]
    fn hook_refuses_for_antigravity() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        let res = run(&mut out, &mut err, "antigravity");
        assert!(res.is_err());
    }

    #[test]
    fn hook_errors_on_unknown_platform() {
        let mut out = Vec::new();
        let mut err = Vec::new();
        let res = run(&mut out, &mut err, "made-up-platform");
        assert!(res.is_err());
    }

    /// Round-trip: the emitted command strings should match the form
    /// `mdvs hook handle` actually accepts. Smoke check by parsing the
    /// command via clap.
    #[test]
    fn emitted_commands_parse_as_clap_input() {
        // Quick check: every emitted command starts with `mdvs hook handle
        // --platform <name> --kind <kind>` with `kind` one of the two
        // values clap knows about.
        let mut out = Vec::new();
        let mut err = Vec::new();
        run(&mut out, &mut err, "claude-code").unwrap();
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        for entry in parsed["hooks"]["PostToolUse"].as_array().unwrap() {
            let cmd = entry["hooks"][0]["command"].as_str().unwrap();
            assert!(cmd.starts_with("mdvs hook handle --platform claude-code --kind "));
            let kind = cmd
                .strip_prefix("mdvs hook handle --platform claude-code --kind ")
                .unwrap();
            assert!(
                kind == "validate" || kind == "search-nudge",
                "kind must match clap's value-enum: {kind}"
            );
        }
    }
}
