from_latest_tag = true
ignore_merge_commits = false
branch_whitelist = []
tag_prefix = "v"

pre_bump_hooks = [
    """sed -i 's/^version = ".*"/version = "{{version}}"/' Cargo.toml""",
    "cargo generate-lockfile",
    "git add Cargo.toml Cargo.lock",
]
post_bump_hooks = [
    "git push origin",
    "git push origin {{version_tag}}"
]

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
owner = "edochi"
repository = "mdvs"

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
"""
