#!/usr/bin/env bash
# mdvs validate-on-write hook for Cursor (postToolUse, Edit | Write | MultiEdit).
#
# Reads the tool-call payload from stdin, finds the mdvs vault containing the
# edited file, runs `mdvs check` on the vault, and surfaces violations to the
# agent as a `hookSpecificOutput.additionalContext` JSON envelope on stdout.
# Cursor uses the same envelope shape as Claude Code but with camelCase event
# names (`postToolUse` instead of `PostToolUse`) per the Cursor hooks
# reference at https://cursor.com/docs/hooks.
#
# The hook is non-blocking by design — it ALWAYS exits 0. When `mdvs check`
# reports violations the agent sees them and decides on the next turn whether
# to fix the file or propose a schema update (see the project-rules snippet
# under `mdvs scaffold snippet`).
#
# Requirements: `jq` and `mdvs` on PATH.
#
# NOTE: This script has been ship-tested only against Claude Code. The Cursor
# variant translates the same contract into Cursor's documented schema, but
# the end-to-end loop has not been smoke-tested by us. If you wire this up
# and hit a wiring bug, please open an issue.
#
# Generated by `mdvs scaffold hook --platform cursor`.

set -euo pipefail

# Pull the target file path out of the Edit/Write/MultiEdit tool-call payload.
f=$(jq -r '.tool_input.file_path // empty')
[ -z "$f" ] && exit 0
case "$f" in *.md) ;; *) exit 0 ;; esac

# Walk up from the file's directory to find the vault root (the directory
# containing `mdvs.toml`). If none is found, the file isn't in an mdvs vault
# and the hook stays silent.
dir=$(dirname "$f")
while [ "$dir" != "/" ] && [ ! -f "$dir/mdvs.toml" ]; do
  dir=$(dirname "$dir")
done
[ ! -f "$dir/mdvs.toml" ] && exit 0

# Run the validator. Capture stdout+stderr so any parse failures, missing
# config errors, etc. also reach the agent. Short-circuit silently on exit 0
# (clean — `mdvs check` always emits a "Checked N files — no violations"
# status line, so checking output emptiness isn't a useful gate). On exit 1
# (violations found) or 2 (mdvs error) we want the agent to see the output.
#
# Two runs: markdown for the agent (which parses MD fluently and routes the
# violation into its workflow), pretty for the user (rendered by the harness
# UI). ~8 ms per run post-TODO-0172.
if out_md=$(mdvs check "$dir" --output markdown 2>&1); then
  exit 0
fi
[ -z "$out_md" ] && exit 0
out_pretty=$(mdvs check "$dir" --output pretty 2>&1) || true

# Cap the user-visible systemMessage at MAX_USER_LINES to avoid drowning the
# UI on multi-violation reports. Append a "..." marker if we truncated.
# The agent channel (additionalContext) stays uncapped — the agent reads
# all of it and decides what to surface in its reply.
MAX_USER_LINES=15
if [ "$(printf '%s\n' "$out_pretty" | wc -l)" -gt "$MAX_USER_LINES" ]; then
  out_pretty="$(printf '%s\n' "$out_pretty" | head -n "$MAX_USER_LINES")
..."
fi

# Append a pointer to the mdvs skill on the agent-context channel. Cursor
# reads skills from both `.cursor/skills/` (its native path) and
# `.agents/skills/` (the cross-harness convention). We point at the
# cross-harness path to share the install with Codex/OpenCode/Antigravity.
out_agent="$out_md

---

_To handle this correctly, load the mdvs skill at \`.agents/skills/mdvs/SKILL.md\` (or run \`mdvs scaffold skill\` to print it). The schema-evolution loop section covers when to fix the file vs. propose a \`mdvs.toml\` update._"

# Wrap in Cursor's hook-output envelope. Cursor uses camelCase event names.
#   additionalContext — model-visible, non-blocking; the agent acts on this.
#                       Carries the markdown body plus the skill pointer.
#   systemMessage     — user-visible warning, harness-dependent. Cursor's
#                       support for this field is undocumented; included
#                       for symmetry with Claude Code (harmless if ignored).
jq -n --arg agent "$out_agent" --arg user "$out_pretty" \
  '{hookSpecificOutput: {hookEventName: "postToolUse", additionalContext: $agent},
    systemMessage: $user}'
