#!/usr/bin/env bash
# mdvs search-nudge hook for Codex (PostToolUse, Bash).
#
# Fires on any Bash invocation. If the agent's cwd (from stdin) is inside
# an mdvs vault AND the command is a search-style tool, emit a tip pointing
# at `mdvs search` as a structured alternative.
#
# The hook is non-blocking and informational only — exits 0 unconditionally.
#
# Requirements: `jq` on PATH.
#
# NOTE: Tested end-to-end only on Claude Code. The Codex variant uses the
# same envelope shape (verified against the Codex hooks reference) but the
# full feedback loop has not been smoke-tested by us.
#
# Generated by `mdvs scaffold hook --platform codex`.

set -euo pipefail

payload=$(cat)

cwd=$(printf '%s' "$payload" | jq -r '.cwd // empty')
[ -z "$cwd" ] && cwd=$(pwd)
d="$cwd"
while [ "$d" != "/" ] && [ ! -f "$d/mdvs.toml" ]; do
  d=$(dirname "$d")
done
[ ! -f "$d/mdvs.toml" ] && exit 0

cmd=$(printf '%s' "$payload" | jq -r '.tool_input.command // empty')
case "$cmd" in
  *grep*|*rg\ *|*find\ *|*fd\ *|*ag\ *|*ack\ *|*"git grep"*) ;;
  *) exit 0 ;;
esac

jq -n \
  '{hookSpecificOutput: {hookEventName: "PostToolUse",
    additionalContext: "Tip: `mdvs search` is also available for semantic / hybrid / SQL-filtered search over the KB."}}'
