use std::path::Path;

use serde::Deserialize;

use crate::FieldType;
use crate::discovery::FieldInfo;

/// A discovery snapshot written as `mfv.lock` or `mdvs.lock`.
#[derive(Debug)]
pub struct LockFile {
    /// Metadata about the discovery run.
    pub discovery: LockDiscovery,
    /// Every field found during discovery, with per-file observations.
    pub fields: Vec<LockField>,
}

/// Metadata captured during a discovery run.
#[derive(Debug)]
pub struct LockDiscovery {
    /// Total markdown files matched by the glob.
    pub total_files: usize,
    /// Files that had parseable frontmatter.
    pub files_with_frontmatter: usize,
    /// Glob pattern used for file matching.
    pub glob: String,
    /// ISO 8601 timestamp of when the lock was generated.
    pub generated_at: String,
}

/// A single field entry in the lock file.
#[derive(Debug)]
pub struct LockField {
    /// Field name as it appears in frontmatter.
    pub name: String,
    /// Inferred type.
    pub field_type: FieldType,
    /// Relative paths of files containing this field.
    pub files: Vec<String>,
}

impl LockFile {
    /// Build a lock file from discovery results.
    pub fn from_discovery(
        fields: &[FieldInfo],
        total_files: usize,
        files_with_frontmatter: usize,
        glob: &str,
        generated_at: &str,
    ) -> Self {
        let lock_fields = fields
            .iter()
            .map(|f| LockField {
                name: f.name.clone(),
                field_type: f.field_type.clone(),
                files: f.files.clone(),
            })
            .collect();

        LockFile {
            discovery: LockDiscovery {
                total_files,
                files_with_frontmatter,
                glob: glob.to_string(),
                generated_at: generated_at.to_string(),
            },
            fields: lock_fields,
        }
    }

    /// Serialize to TOML string.
    pub fn to_toml_string(&self) -> String {
        let mut out = String::new();

        out.push_str("# Auto-generated by mfv init. Do not edit.\n");
        out.push_str("# To regenerate: mfv init --force\n\n");

        out.push_str("[discovery]\n");
        out.push_str(&format!("total_files = {}\n", self.discovery.total_files));
        out.push_str(&format!(
            "files_with_frontmatter = {}\n",
            self.discovery.files_with_frontmatter
        ));
        out.push_str(&format!("glob = {:?}\n", self.discovery.glob));
        out.push_str(&format!(
            "generated_at = {:?}\n",
            self.discovery.generated_at
        ));
        out.push('\n');

        for field in &self.fields {
            out.push_str("[[field]]\n");
            out.push_str(&format!("name = {:?}\n", field.name));
            out.push_str(&format!("type = {:?}\n", field.field_type.to_string()));
            let files: Vec<String> = field.files.iter().map(|f| format!("{f:?}")).collect();
            out.push_str(&format!("files = [{}]\n", files.join(", ")));
            out.push('\n');
        }

        out
    }

    /// Load a lock file from a file path.
    pub fn from_file(path: &Path) -> Result<Self, LockError> {
        let content = std::fs::read_to_string(path)?;
        content.parse()
    }
}

/// Errors that can occur when loading a lock file.
#[derive(Debug)]
pub enum LockError {
    /// File I/O error.
    Io(std::io::Error),
    /// TOML deserialization error.
    Parse(toml::de::Error),
}

impl std::fmt::Display for LockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LockError::Io(e) => write!(f, "IO error: {e}"),
            LockError::Parse(e) => write!(f, "TOML parse error: {e}"),
        }
    }
}

impl std::error::Error for LockError {}

impl From<std::io::Error> for LockError {
    fn from(e: std::io::Error) -> Self {
        LockError::Io(e)
    }
}

impl From<toml::de::Error> for LockError {
    fn from(e: toml::de::Error) -> Self {
        LockError::Parse(e)
    }
}

#[derive(Deserialize)]
struct RawLockFile {
    discovery: RawLockDiscovery,
    #[serde(default)]
    field: Vec<RawLockField>,
}

#[derive(Deserialize)]
struct RawLockDiscovery {
    total_files: usize,
    files_with_frontmatter: usize,
    glob: String,
    generated_at: String,
}

#[derive(Deserialize)]
struct RawLockField {
    name: String,
    #[serde(rename = "type")]
    field_type: FieldType,
    #[serde(default)]
    files: Vec<String>,
}

impl std::str::FromStr for LockFile {
    type Err = LockError;

    fn from_str(s: &str) -> Result<Self, LockError> {
        let raw: RawLockFile = toml::from_str(s)?;

        Ok(LockFile {
            discovery: LockDiscovery {
                total_files: raw.discovery.total_files,
                files_with_frontmatter: raw.discovery.files_with_frontmatter,
                glob: raw.discovery.glob,
                generated_at: raw.discovery.generated_at,
            },
            fields: raw
                .field
                .into_iter()
                .map(|f| LockField {
                    name: f.name,
                    field_type: f.field_type,
                    files: f.files,
                })
                .collect(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_discovery_builds_lock() {
        let fields = vec![
            FieldInfo {
                name: "title".to_string(),
                field_type: FieldType::String,
                files: vec!["blog/a.md".to_string(), "blog/b.md".to_string()],
            },
            FieldInfo {
                name: "draft".to_string(),
                field_type: FieldType::Boolean,
                files: vec!["blog/a.md".to_string()],
            },
        ];

        let lock =
            LockFile::from_discovery(&fields, 12, 10, "**", "2025-06-12T10:00:00");

        assert_eq!(lock.discovery.total_files, 12);
        assert_eq!(lock.discovery.files_with_frontmatter, 10);
        assert_eq!(lock.discovery.glob, "**");
        assert_eq!(lock.fields.len(), 2);
        assert_eq!(lock.fields[0].name, "title");
        assert_eq!(lock.fields[0].files.len(), 2);
        assert_eq!(lock.fields[1].name, "draft");
        assert_eq!(lock.fields[1].files.len(), 1);
    }

    #[test]
    fn to_toml_string_format() {
        let lock = LockFile {
            discovery: LockDiscovery {
                total_files: 100,
                files_with_frontmatter: 80,
                glob: "**".to_string(),
                generated_at: "2025-06-12T10:00:00".to_string(),
            },
            fields: vec![
                LockField {
                    name: "title".to_string(),
                    field_type: FieldType::String,
                    files: vec!["a.md".to_string(), "b.md".to_string()],
                },
                LockField {
                    name: "tags".to_string(),
                    field_type: FieldType::StringArray,
                    files: vec!["a.md".to_string()],
                },
            ],
        };

        let toml = lock.to_toml_string();

        assert!(toml.contains("# Auto-generated by mfv init."));
        assert!(toml.contains("[discovery]"));
        assert!(toml.contains("total_files = 100"));
        assert!(toml.contains("files_with_frontmatter = 80"));
        assert!(toml.contains("glob = \"**\""));
        assert!(toml.contains("generated_at = \"2025-06-12T10:00:00\""));
        assert!(toml.contains("[[field]]"));
        assert!(toml.contains("name = \"title\""));
        assert!(toml.contains("type = \"string\""));
        assert!(toml.contains("files = [\"a.md\", \"b.md\"]"));
        assert!(toml.contains("type = \"string[]\""));
    }

    #[test]
    fn roundtrip_toml() {
        let lock = LockFile {
            discovery: LockDiscovery {
                total_files: 10,
                files_with_frontmatter: 8,
                glob: "**".to_string(),
                generated_at: "2025-06-12T10:00:00".to_string(),
            },
            fields: vec![
                LockField {
                    name: "title".to_string(),
                    field_type: FieldType::String,
                    files: vec!["a.md".to_string(), "b.md".to_string()],
                },
                LockField {
                    name: "count".to_string(),
                    field_type: FieldType::Integer,
                    files: vec!["a.md".to_string()],
                },
            ],
        };

        let toml = lock.to_toml_string();
        let parsed: LockFile = toml.parse().expect("should roundtrip");

        assert_eq!(parsed.discovery.total_files, 10);
        assert_eq!(parsed.discovery.files_with_frontmatter, 8);
        assert_eq!(parsed.discovery.glob, "**");
        assert_eq!(parsed.fields.len(), 2);
        assert_eq!(parsed.fields[0].name, "title");
        assert_eq!(parsed.fields[0].field_type, FieldType::String);
        assert_eq!(parsed.fields[0].files, vec!["a.md", "b.md"]);
        assert_eq!(parsed.fields[1].name, "count");
        assert_eq!(parsed.fields[1].field_type, FieldType::Integer);
    }

    #[test]
    fn empty_fields_produces_header_only() {
        let lock = LockFile {
            discovery: LockDiscovery {
                total_files: 5,
                files_with_frontmatter: 0,
                glob: "**".to_string(),
                generated_at: "2025-06-12T10:00:00".to_string(),
            },
            fields: vec![],
        };

        let toml = lock.to_toml_string();
        assert!(toml.contains("[discovery]"));
        assert!(!toml.contains("[[field]]"));
    }
}
