use crate::FieldType;
use crate::discovery::FieldInfo;

/// A discovery snapshot written as `mfv.lock` or `mdvs.lock`.
#[derive(Debug)]
pub struct LockFile {
    /// Metadata about the discovery run.
    pub discovery: LockDiscovery,
    /// Every field found during discovery, with per-file observations.
    pub fields: Vec<LockField>,
}

/// Metadata captured during a discovery run.
#[derive(Debug)]
pub struct LockDiscovery {
    /// Total markdown files matched by the glob.
    pub total_files: usize,
    /// Files that had parseable frontmatter.
    pub files_with_frontmatter: usize,
    /// Glob pattern used for file matching.
    pub glob: String,
    /// ISO 8601 timestamp of when the lock was generated.
    pub generated_at: String,
}

/// A single field entry in the lock file.
#[derive(Debug)]
pub struct LockField {
    /// Field name as it appears in frontmatter.
    pub name: String,
    /// Inferred type.
    pub field_type: FieldType,
    /// Relative paths of files containing this field.
    pub files: Vec<String>,
}

impl LockFile {
    /// Build a lock file from discovery results.
    pub fn from_discovery(
        fields: &[FieldInfo],
        total_files: usize,
        files_with_frontmatter: usize,
        glob: &str,
        generated_at: &str,
    ) -> Self {
        let lock_fields = fields
            .iter()
            .map(|f| LockField {
                name: f.name.clone(),
                field_type: f.field_type.clone(),
                files: f.files.clone(),
            })
            .collect();

        LockFile {
            discovery: LockDiscovery {
                total_files,
                files_with_frontmatter,
                glob: glob.to_string(),
                generated_at: generated_at.to_string(),
            },
            fields: lock_fields,
        }
    }

    /// Serialize to TOML string.
    pub fn to_toml_string(&self) -> String {
        let mut out = String::new();

        out.push_str("# Auto-generated by mfv init. Do not edit.\n");
        out.push_str("# To regenerate: mfv init --force\n\n");

        out.push_str("[discovery]\n");
        out.push_str(&format!("total_files = {}\n", self.discovery.total_files));
        out.push_str(&format!(
            "files_with_frontmatter = {}\n",
            self.discovery.files_with_frontmatter
        ));
        out.push_str(&format!("glob = {:?}\n", self.discovery.glob));
        out.push_str(&format!(
            "generated_at = {:?}\n",
            self.discovery.generated_at
        ));
        out.push('\n');

        for field in &self.fields {
            out.push_str("[[field]]\n");
            out.push_str(&format!("name = {:?}\n", field.name));
            out.push_str(&format!("type = {:?}\n", field.field_type.to_string()));
            let files: Vec<String> = field.files.iter().map(|f| format!("{f:?}")).collect();
            out.push_str(&format!("files = [{}]\n", files.join(", ")));
            out.push('\n');
        }

        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_discovery_builds_lock() {
        let fields = vec![
            FieldInfo {
                name: "title".to_string(),
                field_type: FieldType::String,
                files: vec!["blog/a.md".to_string(), "blog/b.md".to_string()],
            },
            FieldInfo {
                name: "draft".to_string(),
                field_type: FieldType::Boolean,
                files: vec!["blog/a.md".to_string()],
            },
        ];

        let lock =
            LockFile::from_discovery(&fields, 12, 10, "**", "2025-06-12T10:00:00");

        assert_eq!(lock.discovery.total_files, 12);
        assert_eq!(lock.discovery.files_with_frontmatter, 10);
        assert_eq!(lock.discovery.glob, "**");
        assert_eq!(lock.fields.len(), 2);
        assert_eq!(lock.fields[0].name, "title");
        assert_eq!(lock.fields[0].files.len(), 2);
        assert_eq!(lock.fields[1].name, "draft");
        assert_eq!(lock.fields[1].files.len(), 1);
    }

    #[test]
    fn to_toml_string_format() {
        let lock = LockFile {
            discovery: LockDiscovery {
                total_files: 100,
                files_with_frontmatter: 80,
                glob: "**".to_string(),
                generated_at: "2025-06-12T10:00:00".to_string(),
            },
            fields: vec![
                LockField {
                    name: "title".to_string(),
                    field_type: FieldType::String,
                    files: vec!["a.md".to_string(), "b.md".to_string()],
                },
                LockField {
                    name: "tags".to_string(),
                    field_type: FieldType::StringArray,
                    files: vec!["a.md".to_string()],
                },
            ],
        };

        let toml = lock.to_toml_string();

        assert!(toml.contains("# Auto-generated by mfv init."));
        assert!(toml.contains("[discovery]"));
        assert!(toml.contains("total_files = 100"));
        assert!(toml.contains("files_with_frontmatter = 80"));
        assert!(toml.contains("glob = \"**\""));
        assert!(toml.contains("generated_at = \"2025-06-12T10:00:00\""));
        assert!(toml.contains("[[field]]"));
        assert!(toml.contains("name = \"title\""));
        assert!(toml.contains("type = \"string\""));
        assert!(toml.contains("files = [\"a.md\", \"b.md\"]"));
        assert!(toml.contains("type = \"string[]\""));
    }

    #[test]
    fn empty_fields_produces_header_only() {
        let lock = LockFile {
            discovery: LockDiscovery {
                total_files: 5,
                files_with_frontmatter: 0,
                glob: "**".to_string(),
                generated_at: "2025-06-12T10:00:00".to_string(),
            },
            fields: vec![],
        };

        let toml = lock.to_toml_string();
        assert!(toml.contains("[discovery]"));
        assert!(!toml.contains("[[field]]"));
    }
}
