use crate::FieldType;
use crate::discovery::FieldInfo;

#[derive(Debug)]
pub struct LockFile {
    pub discovery: LockDiscovery,
    pub fields: Vec<LockField>,
}

#[derive(Debug)]
pub struct LockDiscovery {
    pub total_files: usize,
    pub files_with_frontmatter: usize,
    pub glob: String,
    pub threshold: f64,
    pub generated_at: String,
}

#[derive(Debug)]
pub struct LockField {
    pub name: String,
    pub field_type: FieldType,
    pub count: usize,
    pub promoted: bool,
}

impl LockFile {
    /// Build a lock file from discovery results.
    pub fn from_discovery(
        fields: &[FieldInfo],
        total_files: usize,
        files_with_frontmatter: usize,
        glob: &str,
        threshold: f64,
        generated_at: &str,
    ) -> Self {
        let lock_fields = fields
            .iter()
            .map(|f| LockField {
                name: f.name.clone(),
                field_type: f.field_type.clone(),
                count: f.count,
                promoted: f.promoted,
            })
            .collect();

        LockFile {
            discovery: LockDiscovery {
                total_files,
                files_with_frontmatter,
                glob: glob.to_string(),
                threshold,
                generated_at: generated_at.to_string(),
            },
            fields: lock_fields,
        }
    }

    /// Serialize to TOML string.
    pub fn to_toml_string(&self) -> String {
        let mut out = String::new();

        out.push_str("# Auto-generated by mfv init. Do not edit.\n");
        out.push_str("# To regenerate: mfv init --force\n\n");

        out.push_str("[discovery]\n");
        out.push_str(&format!("total_files = {}\n", self.discovery.total_files));
        out.push_str(&format!(
            "files_with_frontmatter = {}\n",
            self.discovery.files_with_frontmatter
        ));
        out.push_str(&format!("glob = {:?}\n", self.discovery.glob));
        out.push_str(&format!("threshold = {}\n", self.discovery.threshold));
        out.push_str(&format!(
            "generated_at = {:?}\n",
            self.discovery.generated_at
        ));
        out.push('\n');

        for field in &self.fields {
            out.push_str("[[field]]\n");
            out.push_str(&format!("name = {:?}\n", field.name));
            out.push_str(&format!("type = {:?}\n", field.field_type.to_string()));
            out.push_str(&format!("count = {}\n", field.count));
            out.push_str(&format!("promoted = {}\n", field.promoted));
            out.push('\n');
        }

        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_discovery_builds_lock() {
        let fields = vec![
            FieldInfo {
                name: "title".to_string(),
                field_type: FieldType::String,
                count: 10,
                promoted: true,
            },
            FieldInfo {
                name: "draft".to_string(),
                field_type: FieldType::Boolean,
                count: 3,
                promoted: false,
            },
        ];

        let lock = LockFile::from_discovery(&fields, 12, 10, "**/*.md", 0.5, "2025-06-12T10:00:00");

        assert_eq!(lock.discovery.total_files, 12);
        assert_eq!(lock.discovery.files_with_frontmatter, 10);
        assert_eq!(lock.discovery.glob, "**/*.md");
        assert_eq!(lock.discovery.threshold, 0.5);
        assert_eq!(lock.fields.len(), 2);
        assert_eq!(lock.fields[0].name, "title");
        assert!(lock.fields[0].promoted);
        assert_eq!(lock.fields[1].name, "draft");
        assert!(!lock.fields[1].promoted);
    }

    #[test]
    fn to_toml_string_format() {
        let lock = LockFile {
            discovery: LockDiscovery {
                total_files: 100,
                files_with_frontmatter: 80,
                glob: "**/*.md".to_string(),
                threshold: 0.5,
                generated_at: "2025-06-12T10:00:00".to_string(),
            },
            fields: vec![
                LockField {
                    name: "title".to_string(),
                    field_type: FieldType::String,
                    count: 80,
                    promoted: true,
                },
                LockField {
                    name: "tags".to_string(),
                    field_type: FieldType::StringArray,
                    count: 60,
                    promoted: true,
                },
            ],
        };

        let toml = lock.to_toml_string();

        assert!(toml.contains("# Auto-generated by mfv init."));
        assert!(toml.contains("[discovery]"));
        assert!(toml.contains("total_files = 100"));
        assert!(toml.contains("files_with_frontmatter = 80"));
        assert!(toml.contains("glob = \"**/*.md\""));
        assert!(toml.contains("threshold = 0.5"));
        assert!(toml.contains("generated_at = \"2025-06-12T10:00:00\""));
        assert!(toml.contains("[[field]]"));
        assert!(toml.contains("name = \"title\""));
        assert!(toml.contains("type = \"string\""));
        assert!(toml.contains("count = 80"));
        assert!(toml.contains("promoted = true"));
        assert!(toml.contains("type = \"string[]\""));
    }

    #[test]
    fn empty_fields_produces_header_only() {
        let lock = LockFile {
            discovery: LockDiscovery {
                total_files: 5,
                files_with_frontmatter: 0,
                glob: "**/*.md".to_string(),
                threshold: 0.5,
                generated_at: "2025-06-12T10:00:00".to_string(),
            },
            fields: vec![],
        };

        let toml = lock.to_toml_string();
        assert!(toml.contains("[discovery]"));
        assert!(!toml.contains("[[field]]"));
    }
}
